ktor:
    application:
        modules:
            - com.ofebles.ApplicationKt.module
    deployment:
        port: 8080
        watch:
            - classes
            - resources
    development: true
