name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 22
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '22'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build Docker image
        run: docker build -t ofebles/apps:ktor-planning-poker-latest .

      - name: Tag Docker image with date
        run: |
          DATE_TAG=$(date +'%Y%m%d')
          docker tag ofebles/apps:ktor-planning-poker-latest ofebles/apps:ktor-planning-poker-$DATE_TAG

      - name: Log in to Docker Hub
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Docker image
        run: |
          docker push ofebles/apps:ktor-planning-poker-latest
          DATE_TAG=$(date +'%Y%m%d')
          docker push ofebles/apps:ktor-planning-poker-$DATE_TAG
